### ISSUE TITLE
How do you run it?

### ISSUE THREAD

**Issue by Samsung03** [JohnathanLP/populousgame#1]
'Samuel@Pluto~/Desktop/populousgame-master $ ./compile.sh 
Samuel@Pluto~/Desktop/populousgame-master $ ./PG
Segmentation fault'

I have tried going into game.hpp and changing HIGHT and WIDE smaller but it doesnt work

**Comment by JohnathanLP** [comment]
You don't want to change HIGH and WIDE at all, that will cause issues. The game is still in development, and I haven't even looked at it in a week since I started my new job. I may have left it broken. Try to download again, don't change anything, and run it.
